이메일 인증 코드 발송, 검증 기능 추가
Genshin-Flow/GenshinFlow_Be pull request #12
Opened 2024-10-18 10:14 UTC by Preasim

2024-10-21 12:52 UTC, BaeRoNuI requested changes
말씀드려야되나 고민좀 많이 했는데..
전체적으로 메소드명이나 변수명등이 일관성이 없고 난해해 보입니다..
e.g.) 인증메일을 전송하는 `joinEmail`, 메일 발송자를 의미하는 `setFrom` 등..

이런 점으로 인해 코드를 이해하기 어려워지고 태클을 거는 식의 리뷰밖에 진행하기가 어렵습니다..
신경 조금만 더 써주시면 감사하겠습니다.

2024-10-21 12:52 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/application/user/service/MailSendService.java
> +        Random num = new Random();
Java의 Random 은 [사용하지 않는 것이 좋습니다.](https://developer-cheol.tistory.com/86)
ThreadLocalRandom 이나 SecureRandom 등으로 바꾸는 것이 좋을 것 같아요.
또한, num 이라는 명명으로 부터 Random 의 instance 라는 것을 알아내기는 어려워 보입니다.

2024-10-21 12:52 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/application/user/controller/AuthController.java
> +        return mailSendService.joinEmail(mailRequest.getEmail());
method 명은 왠만하면 동사나 동사구로 작성하는것이 권장됩니다.
그리고 URI 를 디자인 하실때는 [kebab-case 를 사용해주시는 것](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Why-you-should-make-kebab-case-a-URL-naming-convention-best-practice)이 좋습니다.
그리고 sendMail(로바꾼다고 가정하고) 이라는 메소드 명과 joinEmail 이라는 코드는.. 앞뒤가 잘 맞지는 않는 것 같아요.

2024-10-21 12:52 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/application/user/dto/auth/SignUpRequest.java
>  @Builder
이전에 말씀드렸던 것 처럼..

2024-10-21 12:52 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/application/user/controller/AuthController.java
> +        return mailSendService.joinEmail(mailRequest.getEmail());
동작 관련해서, email 로 인증코드를 발송했는데 String 으로 인증값을 반환하는 이유는 무엇일까요?

크롬 개발자모드만 사용할 줄 알아도 인증코드를 바로 볼 수 있을 것 같습니다..

2024-10-21 12:52 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/application/user/service/MailSendService.java
> +            throw new RuntimeException("Failed to wend email", e);
오타난것 같아요 + 저희가 의도한 에러이기에 BusinessLogicException을 반환해서 ControllerAdvice로 태우는 것이 맞을 것 같습니다

2024-10-21 12:52 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/util/RedisUtil.java
> +public class RedisUtil {
Redis 라고 하는 서버 외부로의 req/res 를 수행하기에 util 보다는 repository 나 client 라는 명명법이 더 적절하지 않을까 합니다.

2024-10-22 09:14 UTC, Preasim commented on src/main/java/com/next/genshinflow/application/user/service/MailSendService.java
> +        Random num = new Random();
좋은 정보 알려주셔서 감사합니다!

2024-10-22 09:16 UTC, Preasim commented on src/main/java/com/next/genshinflow/application/user/controller/AuthController.java
> +        return mailSendService.joinEmail(mailRequest.getEmail());
테스트할 때마다 이메일을 일일이 확인하는 것이 귀찮아서 인증값을 반환하도록 하고 수정을 하지 않았습니다 죄송합니다 ㅠㅠ

dto 이름도 동사나 동사구로 작성하는 것이 좋을까요?

2024-10-22 10:44 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/application/user/controller/AuthController.java
> +        return mailSendService.joinEmail(mailRequest.getEmail());
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

참고 부탁드릴게요.

개인적인 선호는 글처럼 자연스럽게 읽고 이해할 수 있는 코드가 좋다고 생각합니다.

2024-10-22 10:46 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/application/user/controller/AuthController.java
> +        return mailSendService.joinEmail(mailRequest.getEmail());
다른 리뷰들, 어떻게 네이밍을 할것이냐 자체는 그냥 제 의견을 드린 것 뿐이예요. 하지만 언어 자체의 컨벤션은 지켜야 하지 않을까 싶습니다

2024-11-04 06:33 UTC, Preasim commented
네이밍이나 코드에서 이해하기 어려운 부분이 있으면 모두 말씀해주시면 수정하겠습니다 😊

2024-11-15 07:26 UTC, merged