Feature/jwt auth
Genshin-Flow/GenshinFlow_Be pull request #9
Opened 2024-09-19 00:57 UTC by Preasim

회원가입 후 로그인 시, 액세스 토큰과 리프레시 토큰이 발급되도록 구현했습니다.
액세스 토큰이 만료될 경우, /refresh 엔드포인트로 요청하여 토큰을 재발급받을 수 있도록 설정했습니다.

회원가입 시, 이름과 이미지 등의 정보는 아직 UID를 통해 가져온 API 정보를 반영하는 로직이 완성되지 않아 제외되었습니다.

현재 테스트 목적으로 로컬과 서버의 yml 파일을 모두 변경한 상태이며, 문제 있는 부분이 발견되면 즉시 수정하겠습니다.

2024-09-25 08:06 UTC, Preasim commented
리뷰 시 혼동이 발생할 수 있을 것 같아, fetch-api-userData 브랜치를 삭제하고 내용을 jwt-auth 브랜치에 병합했습니다.

2024-10-06 06:19 UTC, BaeRoNuI requested changes

2024-10-06 06:19 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/application/user/service/ApiService.java
> +
현재 callExternalApi 를 호출할때 마다 webclient를 새로 만들고 있습니다.
@Configuration 을 따로 만들어 webClient bean 을 따로 만들고, 사용하는게 좋아 보입니다.

추가로, Spring boot 3.2 부터는 webClient 처럼 사용할 수 있는 RestClient 를 지원해요. 사용하시는 부분 보니 모두 block() 를 호출해서 사실상 webClient 의 이점이 사라지게 되는데요. HttpInterface + RestClient 사용 검토 부탁드릴게요

2024-10-06 06:19 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/security/jwt/TokenProvider.java
> +            // 보안 이슈 발생 시 HS512로 변경 요망
보안 알고리즘을 HS512 -> HS256 으로 바꾼다고 API 성능이 그렇게 크게 바뀌지 않습니다. API 성능 최적화는 이런 점보다는 DB 쿼리 최적화, trasaction 분리를 바라보는게 더 맞습니다.

무엇보다 보안은 타협의 여지가 있는 분야가 아니라고 생각하는데요. 검토 부탁드릴게요

2024-10-06 06:19 UTC, BaeRoNuI commented on src/main/resources/application-local.yml
> +  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
github action 에 secret 이 있을건데요 거기에 옮겨주세요.
그리고 혹시 가능하시면 이 secret 들어있는 커밋 까지 뒤로 가신다음에 지우고, force push 부탁드릴게요.

2024-10-06 06:19 UTC, BaeRoNuI commented on src/main/resources/application.yaml
> +  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
여기도요

2024-10-06 06:19 UTC, BaeRoNuI commented on src/test/resources/application.yaml
> +  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
여기도요

2024-10-08 22:03 UTC, Preasim commented
jwt secret에 대한 리뷰 내용은 삭제했습니다

2024-10-15 08:43 UTC, Preasim commented
분명 읽었었는데 빼먹었던 것 같아요 죄송합니다.
RestClient는 몰랐던 기술인데 많은 도움이 되었습니다 감사합니다!

2024-10-16 12:46 UTC, BaeRoNuI approved these changes

2024-10-16 12:46 UTC, BaeRoNuI commented
고생하셨슴다

2024-10-17 09:03 UTC, merged

2024-10-22 11:01 UTC, BaeRoNuI commented on src/main/java/com/next/genshinflow/domain/report/entity/ReportEntity.java
>  }
이거 지금 다시 확인했는데 어떤 의도일까요

2024-10-22 11:13 UTC, Preasim commented on src/main/java/com/next/genshinflow/domain/report/entity/ReportEntity.java
>  }
별다른 의도는 없습니다 UserStatus가 없어서 오류가 발생해 임시로 조치해 놓았습니다.

2024-10-22 11:43 UTC, Preasim commented on src/main/java/com/next/genshinflow/domain/report/entity/ReportEntity.java
>  }
아마도 ReportStatus가 UserStatus로 변경되었다가 현재 AccountStatus로 다시 변경되면서 혼란이 생긴 것 같습니다.
신고 기능 쪽은 erd를 다시 검토해야 할 것 같습니다